version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache-notas
    build:
      dockerfile: Dockerfile
    depends_on:
      - maria-db-notas
    volumes:
      - C:/containers/php_apache:/var/www/html/
    ports:
      - 6996:80
  maria-db-notas:
    container_name: maria-db-notas
    image: mariadb:10.9.4
    restart: always
    volumes:
      - C:\containers\mariadb_notas:/var/lib/mysql
    environment:
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
